login_login:
    pattern:  /login
    defaults: { _controller: LoginBundle:Default:login }

login_login_check:
    pattern:  /login_check

login_logout:
    pattern:  /logout

login_solicitar_restablecer_password:
    pattern:  /solicitar-restablecer-password
    defaults: { _controller: LoginBundle:Default:solicitarRestablecerPassword }
    
login_restablecer_password:
    pattern:  /restablecer-password
    defaults: { _controller: LoginBundle:Default:restablecerPassword }