extranet_paciente_listar:
    pattern:  /paciente/listar
    defaults: { _controller: ExtranetBundle:Default:listar }

extranet_paciente_nuevo:
    pattern:  /paciente/nuevo
    defaults: { _controller: ExtranetBundle:Default:nuevo }

extranet_paciente_editar:
    pattern:  /paciente/editar/{id}
    defaults: { _controller: ExtranetBundle:Default:editar }

extranet_paciente_ver:
    pattern:  /paciente/ver/{id}
    defaults: { _controller: ExtranetBundle:Default:ver }

extranet_perfil_editar:
    pattern:  /perfil/editar
    defaults: { _controller: ExtranetBundle:Perfil:editar }