parameters:
#    extranet.example.class: Oxigeno\ExtranetBundle\Example

services:
#    extranet.example:
#        class: %extranet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
