terapia_kinesiologica:
    resource: "@TerapiaKinesiologicaBundle/Resources/config/routing.yml"
    prefix:   /

secretaria:
    resource: "@SecretariaBundle/Resources/config/routing.yml"
    prefix:   /

seguridad:
    resource: "@SeguridadBundle/Resources/config/routing.yml"
    prefix:   /

terapia_hiperbarica:
    resource: "@TerapiaHiperbaricaBundle/Resources/config/routing.yml"
    prefix:   /

paciente:
    resource: "@PacienteBundle/Resources/config/routing.yml"
    prefix:   /extranet


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
