security:
    firewalls:
        extranet:
            pattern:   ^/
            provider:  administrador
            anonymous: ~
            form_login: 
                login_path: seguridad_login
                check_path: seguridad_login_check
                default_target_path: paciente_listar
            logout:
                path:       seguridad_logout
                target:     seguridad_login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/*, roles: ROLE_ADMINISTRADOR }
        
    providers:
        administrador:
            entity: { class: Oxigeno\Extranet\SeguridadBundle\Entity\Administrador, property: nombre }
    
    encoders:
        Oxigeno\Extranet\SeguridadBundle\Entity\Administrador: { algorithm: sha512 }