security:
    firewalls:
        extranet:
            pattern:   ^/
            provider:  administrador
            anonymous: ~
            form_login: 
                login_path: login_login
                check_path: login_login_check
                default_target_path: extranet_paciente_listar
            logout:
                path:       login_logout
                target:     login_login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/*, roles: ROLE_ADMINISTRADOR }
        
    providers:
        administrador:
            entity: { class: Oxigeno\LoginBundle\Entity\Administrador, property: nombre }
    
    encoders:
        Oxigeno\LoginBundle\Entity\Administrador: { algorithm: sha512 }