parameters:
#    seguridad.example.class: Oxigeno\Extranet\SeguridadBundle\Example

services:
#    seguridad.example:
#        class: %seguridad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
